import sqlalchemy as sa

from geoalchemy2 import Geometry
from hcme.db import Base


class Location(Base):

    __tablename__ = "locations"

    coordinates = sa.Column(Geometry("POINT", spatial_index=False, srid=4326))

    area = sa.Column(sa.Float, nullable=False)

    # FK to TAZ
    taz_id = sa.Column(sa.Integer, sa.ForeignKey("tazs.id"), nullable=False)

    # Relationships
    taz = sa.orm.relationship("TAZ", back_populates="locations")

    households = sa.orm.relationship("Household", back_populates="location")


# Manually override the spatial index to ensure alembic auto-migrations do
# not delete postGIS autogenerated indices
sa.Index("locations_coordinates_gist", Location.coordinates, postgresql_using="gist")
