[hcme]
database_url = "postgresql:///hcme"

# Input data directory
input_dir = "./data/inputs/"

# Output data directory
output_dir = "./data/output/"

# Whether to create artifact directories
create_directories = false

beam_dir = ""
beam_conf = ""
java_exec_path = "/usr/bin/java"
mapbox_token = ""

    [hcme.input_files]
    apns = "apns.csv"
    aggregated_tazs = "aggregated-taz.kml"
    drivers = "drivers.txt"
    cities = ""
    census_blocks = ""
    apns_geocoded = ""
    census_blocks_geocoded = ""
    gtfs_dir = "gtfs"

    [hcme.artifacts]
    census_block_address_samples = "census/census_block_address_samples.csv"
    census_block_centroids = "census/census_block_centroids.csv"
    census_block_rep_points = "census/census_block_rep_points.csv"
    population = "beam/population.xml"
    households = "beam/households.xml"
    population_attributes = "beam/populationAttributes.xml"
    household_attributes = "beam/householdAttributes.xml"
    vehicles = "beam/vehicles.csv"
    fleet_vehicles = "beam/fleet_vehicles.csv"
    population_clusters = "demand/"