[hcme]
DATABASE_URL = "postgresql:///hcme"
INPUT_DIR = "./data/inputs/"
OUTPUT_DIR = "./data/output/"

    [hcme.input_files]
    apns = "apns.csv"
    aggregated_tazs = "aggregated-taz.kml"
    drivers = "drivers.txt"