"""add zone type to location

Revision ID: 4d0404fc1920
Revises: 077a31cd58df
Create Date: 2021-11-02 15:18:22.264239

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "4d0404fc1920"
down_revision = "077a31cd58df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column("zone_type", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "zone_type")
    # ### end Alembic commands ###
