"""Add export hooks

Revision ID: a0762dc725bc
Revises: 26f2d6b4a37e
Create Date: 2021-11-23 16:21:46.058492

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a0762dc725bc"
down_revision = "26f2d6b4a37e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column(
            "export_hooks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "export_hooks")
    # ### end Alembic commands ###
