"""create location attributes

Revision ID: 077a31cd58df
Revises: 935eb9413d58
Create Date: 2021-11-02 14:16:26.845208

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "077a31cd58df"
down_revision = "935eb9413d58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("parcel_id", sa.INTEGER(), nullable=False))
    op.add_column("locations", sa.Column("use", sa.String(length=50), nullable=False))
    op.add_column(
        "locations",
        sa.Column("parcel_type", sa.String(length=50), nullable=False),
    )
    op.add_column("locations", sa.Column("weight", sa.Float(), nullable=False))
    op.alter_column(
        "locations",
        "coordinates",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=False,
    )
    op.create_index(
        "ix_locations_use_parcel_type",
        "locations",
        ["use", "parcel_type"],
        unique=False,
    )
    op.create_unique_constraint(None, "locations", ["parcel_id"])
    op.drop_column("locations", "area")
    op.drop_column("persons", "age")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "locations",
        sa.Column(
            "area",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "locations", type_="unique")
    op.drop_index("ix_locations_use_parcel_type", table_name="locations")
    op.alter_column(
        "locations",
        "coordinates",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=True,
    )
    op.drop_column("locations", "weight")
    op.drop_column("locations", "parcel_type")
    op.drop_column("locations", "use")
    op.drop_column("locations", "parcel_id")
    # ### end Alembic commands ###
