"""fix grain on censusblock age

Revision ID: 0fc3f732f2a8
Revises: 3d72da936617
Create Date: 2021-11-10 14:20:58.828069

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fc3f732f2a8"
down_revision = "3d72da936617"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "census_block_age_block_id_sex", "census_block_age", type_="unique"
    )
    op.create_unique_constraint(
        "census_block_age_block_id_sex_agerange",
        "census_block_age",
        ["block_id", "sex", "lower_bound"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "census_block_age_block_id_sex_agerange",
        "census_block_age",
        type_="unique",
    )
    op.create_unique_constraint(
        "census_block_age_block_id_sex",
        "census_block_age",
        ["block_id", "sex"],
    )
    # ### end Alembic commands ###
