"""Fix unique constraint

Revision ID: 936839dbf59b
Revises: e12061fecde4
Create Date: 2021-11-16 11:09:47.229525

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "936839dbf59b"
down_revision = "e12061fecde4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_trips_person_origin_destination", "trips", type_="unique"
    )
    op.create_unique_constraint(
        "uq_trips_person_trip_leg", "trips", ["person_id", "trip_leg"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_trips_person_trip_leg", "trips", type_="unique")
    op.create_unique_constraint(
        "uq_trips_person_origin_destination",
        "trips",
        ["person_id", "origin_location_id", "destination_location_id"],
    )
    # ### end Alembic commands ###
