"""Add person and location FKs to trips

Revision ID: e12061fecde4
Revises: 1fc34cf2ad1d
Create Date: 2021-11-16 11:09:04.176723

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "e12061fecde4"
down_revision = "1fc34cf2ad1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips", sa.Column("person_id", sa.Integer(), nullable=False)
    )
    op.add_column("trips", sa.Column("trip_leg", sa.Integer(), nullable=False))
    op.add_column(
        "trips", sa.Column("origin_location_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "trips",
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
    )
    op.create_unique_constraint(
        "uq_trips_person_origin_destination",
        "trips",
        ["person_id", "origin_location_id", "destination_location_id"],
    )
    op.create_foreign_key(None, "trips", "persons", ["person_id"], ["id"])
    op.create_foreign_key(
        None, "trips", "locations", ["destination_location_id"], ["id"]
    )
    op.create_foreign_key(
        None, "trips", "locations", ["origin_location_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_constraint(
        "uq_trips_person_origin_destination", "trips", type_="unique"
    )
    op.drop_column("trips", "destination_location_id")
    op.drop_column("trips", "origin_location_id")
    op.drop_column("trips", "trip_leg")
    op.drop_column("trips", "person_id")
    # ### end Alembic commands ###
