"""add metrics table

Revision ID: 1fc34cf2ad1d
Revises: bb51990fda40
Create Date: 2021-11-13 14:11:33.593599

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1fc34cf2ad1d"
down_revision = "bb51990fda40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("provenance", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "domain", "name", name="uq_world_metrics_domain_name"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metrics")
    # ### end Alembic commands ###
