"""Change trip date time to interval

Revision ID: 3afbc980f375
Revises: 936839dbf59b
Create Date: 2021-11-16 12:09:18.445885

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3afbc980f375"
down_revision = "936839dbf59b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips", sa.Column("departure", sa.Interval(), nullable=False)
    )
    op.drop_column("trips", "departure_time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips",
        sa.Column(
            "departure_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("trips", "departure")
    # ### end Alembic commands ###
