"""Index location table

Revision ID: ef08bb73a16f
Revises: 72cd88dc88ba
Create Date: 2021-11-29 10:10:34.501759

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef08bb73a16f"
down_revision = "72cd88dc88ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_locations_city"), "locations", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_locations_residential"),
        "locations",
        ["residential"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_use"), "locations", ["use"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_use"), table_name="locations")
    op.drop_index(op.f("ix_locations_residential"), table_name="locations")
    op.drop_index(op.f("ix_locations_city"), table_name="locations")
    # ### end Alembic commands ###
