"""add unique constraint to location

Revision ID: 952d7eedb19b
Revises: 4d0404fc1920
Create Date: 2021-11-02 15:40:57.083247

"""
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "952d7eedb19b"
down_revision = "4d0404fc1920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_locations_parcel_id_taz_id", "locations", ["parcel_id", "taz_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_locations_parcel_id_taz_id", "locations", type_="unique"
    )
    # ### end Alembic commands ###
