"""update grain on census block

Revision ID: 3d72da936617
Revises: a3034f328b4a
Create Date: 2021-11-10 14:18:41.417991

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3d72da936617"
down_revision = "a3034f328b4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "census_block",
        sa.Column("block_code", sa.String(length=4), nullable=False),
    )
    op.drop_constraint(
        "census_block_state_code_county_code_tract_code_key",
        "census_block",
        type_="unique",
    )
    op.create_unique_constraint(None, "census_block", ["id"])
    op.create_unique_constraint(
        None,
        "census_block",
        ["state_code", "county_code", "tract_code", "block_code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "census_block", type_="unique")
    op.drop_constraint(None, "census_block", type_="unique")
    op.create_unique_constraint(
        "census_block_state_code_county_code_tract_code_key",
        "census_block",
        ["state_code", "county_code", "tract_code"],
    )
    op.drop_column("census_block", "block_code")
    # ### end Alembic commands ###
