import sqlalchemy as sa
from geoalchemy2 import Geometry
from hcme.db import Base


class Trip(Base):

    __tablename__ = "trips"

    departure_time = sa.Column(
        sa.DateTime(timezone=True),
        nullable=False,
    )

    origin = sa.Column(Geometry("POINT", spatial_index=False, srid=4326))

    destination = sa.Column(Geometry("POINT", spatial_index=False, srid=4326))


# Manually override the spatial index to ensure alembic auto-migrations do
# not delete postGIS autogenerated indices
sa.Index("idx_trip_origin", Trip.origin, postgresql_using="gist")
sa.Index("idx_trip_destination", Trip.destination, postgresql_using="gist")
